-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.1.31-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win32
-- HeidiSQL Version:             9.5.0.5196
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Dumping database structure for testprogrammer
CREATE DATABASE IF NOT EXISTS `testprogrammer` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `testprogrammer`;

-- Dumping structure for table testprogrammer.kota
CREATE TABLE IF NOT EXISTS `kota` (
  `kode_kota` varchar(15) NOT NULL,
  `NamaKota` varchar(100) NOT NULL,
  `Jenis` varchar(100) NOT NULL,
  `FK_Propinsi` varchar(40) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AVG_ROW_LENGTH=144;

-- Dumping data for table testprogrammer.kota: ~485 rows (approximately)
DELETE FROM `kota`;
/*!40000 ALTER TABLE `kota` DISABLE KEYS */;
INSERT INTO `kota` (`kode_kota`, `NamaKota`, `Jenis`, `FK_Propinsi`) VALUES
	('AC-LGS', 'Langsa ', 'Kota', 'AC'),
	('ADL', 'Konawe Selatan', 'Kabupaten', 'SG'),
	('AFT', 'Maybrat', 'Kota', 'PB'),
	('AGM', 'Bengkulu Utara', 'Kabupaten', 'BE'),
	('AGT', 'Asmat', 'Kabupaten', 'PA'),
	('AKK', 'Labuhanbatu Utara', 'Kabupaten', 'SU'),
	('AMB', 'Ambon', 'Kota', 'MA'),
	('AMR', 'Minahasa Selatan', 'Kabupaten', 'SA'),
	('AMS', 'Sorong', 'Kabupaten', 'PB'),
	('AMT', 'Hulu sungai Utara', 'Kabupaten', 'KS'),
	('APN', 'Tojo Una Una', 'Kabupaten', 'ST'),
	('ARM', 'Minahasa Utara', 'Kabupaten', 'SA'),
	('ARS', 'Solok', 'Kabupaten', 'SB'),
	('ASDF', 'TualASDF', 'KOTA', 'MU'),
	('ATB', 'Belu', 'Kabupaten', 'NT'),
	('BAA', 'Rote Ndao', 'Kabupaten', 'NT'),
	('BALI', 'BANGLITAS', 'KOTA', 'BA'),
	('BAN', 'Bantaeng', 'Kabupaten', 'SN'),
	('BAR', 'Barru', 'Kabupaten', 'SN'),
	('BAU', 'Bau Bau', 'Kota', 'SG'),
	('BBL', 'Brebes', 'Kabupaten', 'JT'),
	('BBU', 'Way kanan', 'Kabupaten', 'LA'),
	('BDG', 'Bandung', 'Kota', 'JB'),
	('BDL', 'Bandar Lampung', 'Kota', 'LA'),
	('BDW', 'Bondowoso', 'Kabupaten', 'JI'),
	('BEK', 'Bengkayang', 'Kabupaten', 'KB'),
	('BEN', 'Kepulauan Selayar', 'Kabupaten', 'SN'),
	('BGK', 'Morowali', 'Kabupaten', 'ST'),
	('BGL', 'Bengkulu', 'Kota', 'BE'),
	('BGR', 'Bogor', 'Kota', 'JB'),
	('BHN', 'Kaur', 'Kabupaten', 'BE'),
	('BIK', 'Biak Numfor', 'Kabupaten', 'PA'),
	('BIM', 'Bima', 'Kota', 'NB'),
	('BIR', 'Birueun', 'Kabupaten', 'AC'),
	('BIT', 'Bitung', 'Kota', 'SA'),
	('BJB', 'Banjarbaru', 'Kota', 'KS'),
	('BJM', 'Banjarmasin', 'Kota', 'KS'),
	('BJN', 'Bojonegoro', 'Kabupaten', 'JI'),
	('BJR', 'Banjar', 'Kota', 'JB'),
	('BJW', 'Ngada', 'Kabupaten', 'NT'),
	('BKJ', 'Gayo Lues', 'Kabupaten', 'AC'),
	('BKL', 'Bangkalan', 'Kabupaten', 'JI'),
	('BKN', 'Kampar', 'Kabupaten', 'RI'),
	('BKO', 'Merangin', 'Kabupaten', 'JA'),
	('BKS', 'Bekasi', 'Kota', 'JB'),
	('BKT', 'Bukittinggi', 'Kota', 'SB'),
	('BLA', 'Blora', 'Kabupaten', 'JT'),
	('BLG', 'Toba Samosir', 'Kabupaten', 'SU'),
	('BLI', 'Bangli', 'Kabupaten', 'BA'),
	('BLN', 'Tanah Bumbu', 'Kabupaten', 'KS'),
	('BLS', 'Bengkalis', 'Kabupaten', 'RI'),
	('BLT', 'Blitar', 'Kota', 'JI'),
	('BLU', 'Bolaang Mongondow Selatan', 'Kabupaten', 'SA'),
	('BNA', 'Banda Aceh', 'Kota', 'AC'),
	('BNG', 'Buton Utara', 'Kabupaten', 'SG'),
	('BNJ', 'Binjai', 'Kota', 'SU'),
	('BNR', 'Banjarnegara', 'Kabupaten', 'JT'),
	('BNT', 'Barito Selatan', 'Kabupaten', 'KT'),
	('BON', 'Bontang', 'Kota', 'KI'),
	('BPD', 'Aceh Barat Daya', 'Kabupaten', 'AC'),
	('BPP', 'Balikpapan', 'Kota', 'KI'),
	('BRB', 'Hulu Sungai tengah', 'Kabupaten', 'KS'),
	('BRG', 'Manggarai Timur', 'Kabupaten', 'NT'),
	('BRK', 'Bolaang Mongondow Utara', 'Kabupaten', 'SA'),
	('BRM', 'Mamberamo Raya', 'Kabupaten', 'PA'),
	('BSB', 'Bintan', 'Kabupaten', 'KR'),
	('BSK', 'Tanah Datar', 'Kabupaten', 'SB'),
	('BT-SRG', 'Serang ', 'Kota', 'BT'),
	('BTA', 'Ogan Komering Ulu', 'Kabupaten', 'SS'),
	('BTG', 'Batang', 'Kabupaten', 'JT'),
	('BTI', 'Teluk Bintuni', 'Kota', 'PB'),
	('BTL', 'Bantul', 'Kabupaten', 'YO'),
	('BTM', 'Batam', 'Kota', 'KR'),
	('BTU', 'Batu', 'Kota', 'JI'),
	('BTW', 'Waropen', 'Kabupaten', 'PA'),
	('BUL', 'Buol', 'Kabupaten', 'ST'),
	('BYL', 'Boyolali', 'Kabupaten', 'JT'),
	('BYW', 'Banyuwangi', 'Kabupaten', 'JI'),
	('CAG', 'Aceh Jaya', 'Kabupaten', 'AC'),
	('CBI', 'Bogor', 'Kabupaten', 'JB'),
	('CBN', 'Cirebon', 'Kota', 'JB'),
	('CJR', 'Cianjur', 'Kabupaten', 'JB'),
	('CKG', 'Jakarta Timur', 'Kota', 'JK'),
	('CKR', 'Bekasi', 'Kabupaten', 'JB'),
	('CLG', 'Cilegon', 'Kota', 'BT'),
	('CLP', 'Cilacap', 'Kabupaten', 'JT'),
	('CMH', 'Cimahi', 'Kota', 'JB'),
	('CMS', 'Ciamis', 'Kabupaten', 'JB'),
	('CPT', 'Tangerang Selatan', 'Kota', 'BT'),
	('CRP', 'Rejang Lebong', 'Kabupaten', 'BE'),
	('DGL', ' Donggala', 'Kabupaten', 'ST'),
	('DKL', 'Lingga', 'Kabupaten', 'KR'),
	('DLS', 'Humbang Hasundutan', 'Kabupaten', 'SU'),
	('DMK', 'Demak', 'Kabupaten', 'JT'),
	('DOB', 'Kepulauan Aru', 'Kabupaten', 'MA'),
	('DP', 'Denpasar ', 'Kota', 'BA'),
	('DPK', 'Depok', 'Kota', 'JB'),
	('DPU', 'Dompu', 'Kabupaten', 'NB'),
	('DRH', 'Seram Bagian barat', 'Kabupaten', 'MA'),
	('DTH', 'Seram Bagian Timur', 'Kabupaten', 'MA'),
	('DUM', 'Dumai', 'Kota', 'RI'),
	('ELL', 'Yalimo', 'Kabupaten', 'PA'),
	('END', 'Ende', 'Kabupaten', 'NT'),
	('ENR', 'Enrekang', 'Kabupaten', 'SN'),
	('ERT', 'Paniai', 'Kabupaten', 'PA'),
	('FEF', 'Tambrauw', 'Kabupaten', 'PB'),
	('FFK', 'Fak Fak', 'Kabupaten', 'PB'),
	('GDT', 'Pesawaran', 'Kabupaten', 'LA'),
	('GGP', 'Jakarta Barat', 'Kota', 'JK'),
	('GIN', 'Gianyar', 'Kabupaten', 'BA'),
	('GNS', 'Lampung Tengah', 'Kabupaten', 'LA'),
	('GNT', 'Padang Lawas Utara', 'Kabupaten', 'SU'),
	('GO-GTO', 'Gorontalo', 'Kota', 'GO'),
	('GRG', 'Lombok Barat', 'Kabupaten', 'NB'),
	('GRT', 'Garut', 'Kabupaten', 'JB'),
	('GSK', 'Gresik', 'Kabupaten', 'JI'),
	('GST', 'Nias', 'Kabupaten', 'SU'),
	('GTO', 'Gorontalo', 'Kabupaten', 'GO'),
	('IDL', 'Ogan Ilir', 'Kabupaten', 'SS'),
	('IDM', 'Indramayu', 'Kabupaten', 'JB'),
	('ILG', 'Puncak', 'Kabupaten', 'PA'),
	('JA-SPN', 'Sungai Penuh ', 'Kota', 'JA'),
	('JAP', 'Jayapura', 'Kabupaten', 'PA'),
	('JBG', 'Jombang', 'Kabupaten', 'JI'),
	('JI-KDR', 'Kediri ', 'Kota', 'JI'),
	('JI-MJK', 'Mojokerto ', 'Kota', 'JI'),
	('JLL', 'Halmahera Barat', 'Kabupaten', 'MU'),
	('JMB', 'Jambi', 'Kota', 'JA'),
	('JMR', 'Jember', 'Kabupaten', 'JI'),
	('JNP', 'Jeneponto', 'Kabupaten', 'SN'),
	('JPA', 'Jepara', 'Kabupaten', 'JT'),
	('JTH', 'Aceh Besar', 'Kabupaten', 'AC'),
	('KAG', 'Ogan Komering Ilir', 'Kabupaten', 'SS'),
	('KBA', 'Bangka Selatan', 'Kabupaten', 'BB'),
	('KBG', 'Tolikara', 'Kabupaten', 'PA'),
	('KBJ', 'Karo', 'Kabupaten', 'SU'),
	('KBK', 'Mamberamo Tengah', 'Kabupaten', 'PA'),
	('KBR', 'Kotabaru', 'Kabupaten', 'KS'),
	('KDI', 'Kendari', 'Kota', 'SG'),
	('KDL', 'Kendal', 'Kabupaten', 'JT'),
	('KDR', 'Kediri', 'Kabupaten', 'JI'),
	('KDS', 'Kudus', 'Kabupaten', 'JT'),
	('KEP', ' Mappi', 'Kabupaten', 'PA'),
	('KFM', 'Timor Tengah Utara', 'Kabupaten', 'NT'),
	('KGM', 'Dogiyai', 'Kabupaten', 'PA'),
	('KGN', 'Hulu Sungai Selatan', 'Kabupaten', 'KS'),
	('KIS ', 'Asahan', 'Kabupaten', 'SU'),
	('KJN', 'Pekalongan', 'Kabupaten', 'JT'),
	('KKA', 'Kolaka', 'Kota', 'SG'),
	('KKN', 'Gunung Mas', 'Kabupaten', 'KT'),
	('KLA', 'Lampung Selatan', 'Kabupaten', 'LA'),
	('KLB', 'Alor', 'Kabupaten', 'NT'),
	('KLK', 'Kapuas', 'Kabupaten', 'KT'),
	('KLN', 'Klaten', 'Kabupaten', 'JT'),
	('KLP', 'Seruyan', 'Kabupaten', 'KT'),
	('KLT', 'Tanjung Jabung Barat', 'Kabupaten', 'JA'),
	('KMN', 'Kaimana', 'Kota', 'PB'),
	('KNG', 'Kuningan', 'Kabupaten', 'JB'),
	('KNR', 'Blitar', 'Kabupaten', 'JI'),
	('KOT', 'Tanggamus', 'Kabupaten', 'LA'),
	('KPG', 'Kupang', 'Kabupaten', 'NT'),
	('KPH', 'Kepahiang', 'Kabupaten', 'BE'),
	('KPI', 'Labuhanbatu Selatan', 'Kabupaten', 'SU'),
	('KPN', 'Kepanjen', 'Kabupaten', 'JI'),
	('KRA', 'Karangasem', 'Kabupaten', 'BA'),
	('KRB', 'Aceh Tamiang', 'Kabupaten', 'AC'),
	('KRG', 'Karanganyar', 'Kabupaten', 'JT'),
	('KRS', 'Probolinggo', 'Kabupaten', 'JI'),
	('KRT', 'Bengkulu Tengah', 'Kabupaten', 'BE'),
	('KSN', 'Katingan', 'Kabupaten', 'KT'),
	('KSU', 'Kepulauan Seribu', 'Kabupaten', 'JK'),
	('KTB', 'Lampung Utara', 'Kabupaten', 'LA'),
	('KTG', 'Kotamobagu', 'Kota', 'SA'),
	('KTN', 'Aceh Tenggara', 'Kabupaten', 'AC'),
	('KTP', 'Ketapang', 'Kabupaten', 'KB'),
	('KWD', 'Gorontalo Utara', 'Kabupaten', 'GO'),
	('KWG', 'Karawang', 'Kabupaten', 'JB'),
	('KYB', 'Jakarta Selatan', 'Kota', 'JK'),
	('KYM', 'Nduga', 'Kabupaten', 'PA'),
	('LBA', 'Halmahera Selatan', 'Kabupaten', 'MU'),
	('LBB', 'Agam', 'Kabupaten', 'SB'),
	('LBJ', 'Manggarai Barat', 'Kabupaten', 'NT'),
	('LBP', 'Deli serdang', 'Kabupaten', 'SU'),
	('LBS', 'Pasaman', 'Kabupaten', 'SB'),
	('LGS', 'Aceh Timur', 'Kabupaten', 'AC'),
	('LHM', 'Nias Barat', 'Kabupaten', 'SU'),
	('LHT', 'Lahat', 'Kabupaten', 'SS'),
	('LIW', 'Lampung Barat', 'Kabupaten', 'LA'),
	('LLG', 'Lubuk Linggau', 'Kota', 'SS'),
	('LLK', 'Bolaang Mongondow', 'Kabupaten', 'SA'),
	('LLS', 'Kolaka Utara', 'Kabupaten', 'SG'),
	('LMG', 'Lamongan', 'Kabupaten', 'JI'),
	('LMJ', 'Lumajang', 'Kabupaten', 'JI'),
	('LMP', 'Batu Bara', 'Kabupaten', 'SU'),
	('LRT', 'Flores Timur', 'Kabupaten', 'NT'),
	('LSK', 'Aceh Utara', 'Kabupaten', 'AC'),
	('LSM', 'Lhokseumawe', 'Kota', 'AC'),
	('LTU', 'Nias Utara', 'Kabupaten', 'SU'),
	('LWK', 'Banggai', 'Kabupaten', 'ST'),
	('LWL', 'Lembata', 'Kabupaten', 'NT'),
	('MA-TUL', 'Tual', 'Kota', 'MA'),
	('MAB', 'Halmahera Timur', 'Kabupaten', 'MU'),
	('MAD', 'Madiun', 'Kota', 'JI'),
	('MAK', 'Tana Toraja', 'Kabupaten', 'SN'),
	('MAM', 'Mamuju', 'Kabupaten', 'SR'),
	('MAR', 'Pahuwato', 'Kabupaten', 'GO'),
	('MBN', 'Batanghari', 'Kabupaten', 'JA'),
	('MBO', 'Aceh Barat', 'Kabupaten', 'AC'),
	('MBY', 'Nagekeo', 'Kabupaten', 'NT'),
	('MDN', 'Medan', 'Kota', 'SU'),
	('MET', 'Metro', 'Kota', 'LA'),
	('MGL', 'Magelang', 'Kota', 'JT'),
	('MGN', 'Kepulauan Talaud', 'Kabupaten', 'SA'),
	('MGR', 'Belitung Timur', 'Kabupaten', 'BB'),
	('MGT', 'Magetan', 'Kabupaten', 'JI'),
	('MGW', 'Badung', 'Kabupaten', 'BA'),
	('MJK', 'Mojokerto', 'Kabupaten', 'JI'),
	('MJL', 'Majalengka', 'Kabupaten', 'JB'),
	('MJN', 'Majene', 'Kabupaten', 'SR'),
	('MJY', 'Madiun', 'Kabupaten', 'JI'),
	('MKM', 'Muko Muko', 'Kabupaten', 'BE'),
	('MKS', 'Makasar', 'Kota', 'SN'),
	('MLB', 'Musi Rawas', 'Kabupaten', 'SS'),
	('MLG', 'Malang', 'Kota', 'JI'),
	('MLL', 'Luwu Timur', 'Kabupaten', 'SN'),
	('MLN', 'Malinau', 'Kabupaten', 'KU'),
	('MME', 'Sikka', 'Kabupaten', 'NT'),
	('MNA', 'Bengkulu Selatan', 'Kabupaten', 'BE'),
	('MND', 'Manado', 'Kota', 'SA'),
	('MNK', 'Manokwari', 'Kabupaten', 'PB'),
	('MPR', 'Oku Timur', 'Kabupaten', 'SS'),
	('MPW', 'Pontianak', 'Kabupaten', 'KB'),
	('MRB', 'Bungo', 'Kabupaten', 'JA'),
	('MRD', 'Oku Selatan', 'Kabupaten', 'SS'),
	('MRE', 'Muara Enim', 'Kabupaten', 'SS'),
	('MRH', 'Barito Kuala', 'Kabupaten', 'KS'),
	('MRJ', 'Sijunjung', 'Kabupaten', 'SB'),
	('MRK', 'Merauke', 'Kabupaten', 'PA'),
	('MRN', 'Pidie Jaya', 'Kabupaten', 'AC'),
	('MRS', 'Maros', 'Kabupaten', 'SN'),
	('MRT', 'Tebo', 'Kabupaten', 'JA'),
	('MSB', 'Luwu Utara', 'Kabupaten', 'SN'),
	('MSH', 'Maluku Tengah', 'Kabupaten', 'MA'),
	('MSJ', 'Mesuji', 'Kabupaten', 'LA'),
	('MSK', 'Tanjung Jabung Timur', 'Kabupaten', 'JA'),
	('MTK', 'Bangka Barat', 'Kabupaten', 'BB'),
	('MTP', 'Banjar', 'Kabupaten', 'KS'),
	('MTR', 'Mataram', 'Kota', 'NB'),
	('MTS', 'Pulau Morotai', 'Kabupaten', 'MU'),
	('MTW', 'Barito Utara', 'Kabupaten', 'KT'),
	('MUL', 'Puncak Jaya', 'Kabupaten', 'PA'),
	('NAB', 'Nabire', 'Kabupaten', 'PA'),
	('NBA', 'Landak', 'Kabupaten', 'KB'),
	('NGA', 'Jembrana', 'Kabupaten', 'BA'),
	('NGW', 'Ngawi', 'Kabupaten', 'JI'),
	('NJK', 'Nganjuk', 'Kabupaten', 'JI'),
	('NLA', 'Buru', 'Kabupaten', 'MA'),
	('NMR', 'Buru Selatan', 'Kabupaten', 'MA'),
	('NNK', 'Nunukan', 'Kabupaten', 'KU'),
	('NPH', 'Bandung Barat', 'Kabupaten', 'JB'),
	('NT-KPG', 'Kupang', 'Kota', 'NT'),
	('OSB', 'Pegunungan Bintang', 'Kabupaten', 'PA'),
	('PA-JAP', 'Jayapura', 'Kota', 'PA'),
	('PAD', 'Padang', 'Kota', 'SB'),
	('PAL', 'Palu', 'Kota', 'ST'),
	('PBG', 'Purbalingga', 'Kabupaten', 'JT'),
	('PBL', 'Probolinggo', 'Kota', 'JI'),
	('PBM', 'Prabumulih', 'Kota', 'SS'),
	('PBR', 'Pekanbaru', 'Kota', 'RI'),
	('PBU', 'Kotawaringin Barat', 'Kabupaten', 'KT'),
	('PCT', 'Pacitan', 'Kabupaten', 'JI'),
	('PDA', 'Solok Selatan', 'Kabupaten', 'SB'),
	('PDG', 'Pandeglang', 'Kabupaten', 'BT'),
	('PDP', 'Padang Panjang', 'Kota', 'SB'),
	('PGA', 'Pagar Alam', 'Kota', 'SS'),
	('PGP', 'Pangkal Pinang', 'Kota', 'BB'),
	('PIN', 'Pinrang', 'Kabupaten', 'SN'),
	('PKB', 'Banyuasin', 'Kabupaten', 'SS'),
	('PKJ', 'Pangkajene Kepulauan', 'Kabupaten', 'SN'),
	('PKK', 'Pelalawan', 'Kabupaten', 'RI'),
	('PKL', 'Pekalongan', 'Kota', 'JT'),
	('PKY', 'Mamuju Utara', 'Kabupaten', 'SR'),
	('PLG', 'Palembang', 'Kota', 'SS'),
	('PLI', 'Tanah Laut', 'Kabupaten', 'KS'),
	('PLJ', 'Dharmasraya', 'Kabupaten', 'SB'),
	('PLK', 'Palangkaraya', 'Kota', 'KT'),
	('PLP', 'Luwu', 'Kabupaten', 'SN'),
	('PLW', 'Polewali Mandar', 'Kabupaten', 'SR'),
	('PMK', 'Pamekasan', 'Kabupaten', 'JI'),
	('PML', 'Pemalang', 'Kabupaten', 'JT'),
	('PMN', 'Pariaman', 'Kota', 'SB'),
	('PMS', 'Simalungun', 'Kabupaten', 'SU'),
	('PNG', 'Ponorogo', 'Kabupaten', 'JI'),
	('PNJ', 'Penajam Paser Utara', 'Kabupaten', 'KI'),
	('PNM', 'Padang Pariaman', 'Kabupaten', 'SB'),
	('PNR', 'Pesisir Selatan', 'Kabupaten', 'SB'),
	('PPS', 'Pulang pisau', 'Kabupaten', 'KT'),
	('PRC', 'Murung Raya', 'Kabupaten', 'KT'),
	('PRE', 'Pare Pare', 'Kota', 'SN'),
	('PRG', 'Parigi Moutong', 'Kabupaten', 'ST'),
	('PRN', 'Balangan', 'Kabupaten', 'KS'),
	('PRP', 'Rokan Hulu', 'Kabupaten', 'RI'),
	('PRR', 'Samosir', 'Kabupaten', 'SU'),
	('PRW', 'Pringsewu', 'Kabupaten', 'LA'),
	('PSN', 'Pasuruan', 'Kota', 'JI'),
	('PSO', 'Poso', 'Kabupaten', 'ST'),
	('PSP', 'Tapanuli Selatan', 'Kabupaten', 'SU'),
	('PSR', 'Pasuruan', 'Kabupaten', 'JI'),
	('PSW', 'Buton', 'Kabupaten', 'SG'),
	('PTI', 'Pati', 'Kabupaten', 'JT'),
	('PTK', 'Pontianak', 'Kota', 'KB'),
	('PTS', 'Kapuas Hulu', 'Kabupaten', 'KB'),
	('PWD', 'Grobogan', 'Kabupaten', 'JT'),
	('PWK', 'Purwakarta', 'Kabupaten', 'JB'),
	('PWR', 'Purworejo', 'Kabupaten', 'JT'),
	('PYA', 'Lombok Tengah', 'Kabupaten', 'NB'),
	('PYB', 'Mandailing Natal', 'Kabupaten', 'SU'),
	('PYH', 'Payakumbuh', 'Kota', 'SB'),
	('RAN', 'Natuna', 'Kabupaten', 'KR'),
	('RAP', 'Labuhanbatu', 'Kabupaten', 'SU'),
	('RAS', 'Teluk Wondama', 'Kota', 'PB'),
	('RBG', 'Rembang', 'Kabupaten', 'JT'),
	('RGB', 'Lamandau', 'Kabupaten', 'KT'),
	('RGT', 'Indragiri Hulu', 'Kabupaten', 'RI'),
	('RKB', 'Lebak', 'Kabupaten', 'BT'),
	('RMB', 'Bombana', 'Kabupaten', 'SG'),
	('RTA', 'Tapin', 'Kabupaten', 'KS'),
	('RTG', 'Manggarai', 'Kabupaten', 'NT'),
	('RTN', 'Minahasa Tenggara', 'Kabupaten', 'SA'),
	('RTP', 'Toraja Utara', 'Kabupaten', 'SN'),
	('SAB', 'Sabang', 'Kota', 'AC'),
	('SAG', 'Sanggau', 'Kabupaten', 'KB'),
	('SAK', 'Siak', 'Kabupaten', 'RI'),
	('SAL ', 'Pakpak Bharat', 'Kabupaten', 'SU'),
	('SBB', 'Sibu Raijua', 'Kabupaten', 'NT'),
	('SBG', 'Tapanuli Tengah', 'Kabupaten', 'SU'),
	('SBH', 'Padang Lawas', 'Kabupaten', 'SU'),
	('SBM', 'Sukabumi', 'Kabupaten', 'JB'),
	('SBR', 'Cirebon', 'Kabupaten', 'JB'),
	('SBS', 'Sambas', 'Kabupaten', 'KB'),
	('SBW', 'Sumbawa', 'Kabupaten', 'NB'),
	('SBY', 'Surabaya', 'Kota', 'JI'),
	('SDA', 'Sidoarjo', 'Kabupaten', 'JI'),
	('SDK', 'Dairi', 'Kabupaten', 'SU'),
	('SDN', 'Lampung Timur', 'Kabupaten', 'LA'),
	('SDR', 'Sidenreng Rappang', 'Kabupaten', 'SN'),
	('SDW', 'Kutai barat', 'Kabupaten', 'KI'),
	('SED', 'Sedakau', 'Kabupaten', 'KB'),
	('SEL', 'Lombok Timur', 'Kabupaten', 'NB'),
	('SGB', 'Sigi', 'Kabupaten', 'ST'),
	('SGI', 'Pidie', 'Kabupaten', 'AC'),
	('SGL', 'Bangka', 'Kabupaten', 'BB'),
	('SGM', 'Gowa', 'Kabupaten', 'SN'),
	('SGN', 'Sragen', 'Kabupaten', 'JT'),
	('SGP', 'Intan Jaya', 'Kabupaten', 'PA'),
	('SGR', 'Buleleng', 'Kabupaten', 'BA'),
	('SGT', 'Kutai Timur', 'Kabupaten', 'KI'),
	('SIT', 'Situbondo', 'Kabupaten', 'JI'),
	('SKB', 'Sukabumi', 'Kota', 'JB'),
	('SKD', 'Kayong Utara', 'Kabupaten', 'KB'),
	('SKG', 'Wajo', 'Kabupaten', 'SN'),
	('SKH', 'Sukoharjo', 'Kabupaten', 'JT'),
	('SKL', 'Aceh Singkil', 'Kabupaten', 'AC'),
	('SKM', 'Nagan Raya', 'Kabupaten', 'AC'),
	('SKN', 'Banggai Kepulauan', 'Kabupaten', 'ST'),
	('SKR', 'Sukamara', 'Kabupaten', 'KT'),
	('SKT', 'Surakarta', 'Kota', 'JT'),
	('SKW', 'Singkawang', 'Kota', 'KB'),
	('SKY', 'Musi Banyuasin', 'Kabupaten', 'SS'),
	('SLK', 'Solok', 'Kota', 'SB'),
	('SLT', 'Salatiga', 'Kota', 'JT'),
	('SLW', 'Tegal', 'Kabupaten', 'JT'),
	('SMD', 'Sumedang', 'Kabupaten', 'JB'),
	('SMG', 'Semarang', 'Kota', 'JT'),
	('SMH', 'Yahukimo', 'Kabupaten', 'PA'),
	('SMI', 'Sarmi', 'Kabupaten', 'PA'),
	('SML', 'Maluku Tenggara Barat', 'Kabupaten', 'MA'),
	('SMN', 'Sleman', 'Kabupaten', 'YO'),
	('SMR', 'Samarinda', 'Kota', 'KI'),
	('SN-PLP', 'Palopo', 'Kota', 'SN'),
	('SNB', 'Simeulue', 'Kabupaten', 'AC'),
	('SNG', 'Subang', 'Kabupaten', 'JB'),
	('SNJ', 'Sinjai', 'Kabupaten', 'SN'),
	('SNN', 'Kepulauan Sula', 'Kabupaten', 'MU'),
	('SNT', 'Muaro Jambi', 'Kabupaten', 'JA'),
	('SOE', 'Timor Tengah Selatan', 'Kabupaten', 'NT'),
	('SON', 'Sorong', 'Kota', 'PB'),
	('SPA', 'Tasikmalaya', 'Kabupaten', 'JB'),
	('SPE', 'Pasaman Barat', 'Kabupaten', 'SB'),
	('SPG', 'Sampang', 'Kabupaten', 'JI'),
	('SPN', 'Kerinci', 'Kabupaten', 'JA'),
	('SPT', 'Kotawaringin Timur', 'Kabupaten', 'KT'),
	('SRG', 'Serang', 'Kabupaten', 'BT'),
	('SRH', 'Serdang Bedagai', 'Kabupaten', 'SU'),
	('SRK', 'Lima Puluh Kota', 'Kabupaten', 'SB'),
	('SRL', 'Sorolangun', 'Kabupaten', 'JA'),
	('SRP', 'Klungkung', 'Kabupaten', 'BA'),
	('SRU', 'Kepulauan Yapen', 'Kabupaten', 'PA'),
	('SRW', 'Supiori', 'Kabupaten', 'PA'),
	('SRY', 'Kubu Raya', 'Kabupaten', 'KB'),
	('STB', 'Langkat', 'Kabupaten', 'SU'),
	('STG', 'Sintang', 'Kabupaten', 'KB'),
	('STR', 'Bener Meriah', 'Kabupaten', 'AC'),
	('SU-GST', 'Gunungsitoli', 'Kota', 'SU'),
	('SU-PMS', 'Pematangsiantar', 'Kota', 'SU'),
	('SU-PSP', 'Padang Sidempuan', 'Kota', 'SU'),
	('SU-SBG', 'Sibolga', 'Kota', 'SU'),
	('SUS', 'Subulussalam', 'Kota', 'AC'),
	('SWL', 'Sawahlunto', 'Kota', 'SB'),
	('SWW', 'Bone bolango', 'Kabupaten', 'GO'),
	('TAB', 'Tabanan', 'Kabupaten', 'BA'),
	('TAM', 'Sumba Barat Daya', 'Kabupaten', 'NT'),
	('TAR', 'Tarakan', 'Kota', 'KU'),
	('TAS', 'Seluma', 'Kabupaten', 'BE'),
	('TBG', 'Empat lawang', 'Kabupaten', 'SS'),
	('TBH', 'Indragiri Hilir', 'Kabupaten', 'RI'),
	('TBK', 'Karimun', 'Kabupaten', 'KR'),
	('TBL', 'Bangka Selatan', 'Kabupaten', 'BB'),
	('TBN', 'Tuban', 'Kabupaten', 'JI'),
	('TBT', 'Tebing Tinggi', 'Kota', 'SU'),
	('TDN', 'Belitung', 'Kabupaten', 'BB'),
	('TDP', 'Tana Kidung', 'Kabupaten', 'KU'),
	('TDR', 'Tidore', 'Kota', 'MU'),
	('TGL', 'Tegal', 'Kota', 'JT'),
	('TGR', 'Tangerang', 'Kabupaten', 'BT'),
	('TGT', 'Paser', 'Kabupaten', 'KI'),
	('THN', 'Kepulauan Sangihe', 'Kabupaten', 'SA'),
	('TIG', 'Dieyai', 'Kabupaten', 'PA'),
	('TIM', 'Mimika', 'Kabupaten', 'PA'),
	('TJB', 'Tanjung Balai', 'Kota', 'SU'),
	('TJG', 'Tabalong', 'Kabupaten', 'KS'),
	('TJN', 'Lombok Utara', 'Kabupaten', 'NB'),
	('TJP', 'Jakarta Utara', 'Kota', 'JK'),
	('TJS', 'Bulungan', 'Kabupaten', 'KU'),
	('TKA', 'Takalar', 'Kabupaten', 'SN'),
	('TKN', 'Aceh Tengah', 'Kabupaten', 'AC'),
	('TKR', 'Maluku Barat Daya', 'Kabupaten', 'MA'),
	('TLD', 'Nias Selatan', 'Kabupaten', 'SU'),
	('TLG', 'Tulungagung', 'Kabupaten', 'JI'),
	('TLI', 'Toli Toli', 'Kabupaten', 'ST'),
	('TLK', 'Kuantan Singingi', 'Kabupaten', 'RI'),
	('TLW', 'Sumbawa Barat', 'Kabupaten', 'NB'),
	('TMB', 'Sorong Selatan', 'Kabupaten', 'PB'),
	('TMG', 'Temanggung', 'Kabupaten', 'JT'),
	('TMH', 'Tomohon', 'Kota', 'SA'),
	('TML', 'Barito Timur', 'Kabupaten', 'KS'),
	('TMR', 'Boven Digoel', 'Kabupaten', 'PA'),
	('TMT', 'Boalemo', 'Kabupaten', 'GO'),
	('TNA', 'Jakarta Pusat', 'Kota', 'JK'),
	('TNG', 'Tangerang', 'Kota', 'BT'),
	('TNN', 'Minahasa', 'Kabupaten', 'SA'),
	('TNR', 'Berau', 'Kabupaten', 'KI'),
	('TOB', 'Halmahera Utara', 'Kabupaten', 'MU'),
	('TOM', 'Lanny Jaya', 'Kabupaten', 'PA'),
	('TPG', 'Tanjung Pinang', 'Kota', 'KR'),
	('TPT', 'Kepulauan Mentawai', 'Kabupaten', 'SB'),
	('TRG', 'Kutai Kertanegara', 'Kabupaten', 'KI'),
	('TRK', 'Trenggalek', 'Kabupaten', 'JI'),
	('TRP', 'Kepulauan Anambas', 'Kabupaten', 'KR'),
	('TSM', 'Tasikmalaya', 'Kota', 'JB'),
	('TTE', 'Ternate', 'Kota', 'MU'),
	('TTG', 'Kepulauan Meranti', 'Kabupaten', 'RI'),
	('TTN', 'Aceh Selatan', 'Kabupaten', 'AC'),
	('TUB', 'Lebong', 'Kabupaten', 'BE'),
	('TUL', 'Maluku Tenggara', 'Kabupaten', 'MA'),
	('TWG', 'Tulang bawang Barat', 'Kabupaten', 'LA'),
	('UJT', 'Rokan Hilir', 'Kabupaten', 'RI'),
	('UNH', 'Konawe', 'Kabupaten', 'SG'),
	('UNR', 'Semarang', 'Kabupaten', 'JT'),
	('WAM', 'Jayawijaya', 'Kabupaten', 'PA'),
	('WAS', 'Raja Ampat', 'Kabupaten', 'PB'),
	('WAT', 'Kulon Progo', 'Kabupaten', 'YO'),
	('WBL', 'Sumba Tengah', 'Kabupaten', 'NT'),
	('WED', 'Halmahera Tengah', 'Kabupaten', 'MU'),
	('WGD', 'Konawe Utara', 'Kabupaten', 'SG'),
	('WGP', 'Sumba Timur', 'Kabupaten', 'NT'),
	('WGW', 'Wakatobi', 'Kabupaten', 'SG'),
	('WHO', 'Bima', 'Kabupaten', 'NB'),
	('WKB', 'Sumba Barat', 'Kabupaten', 'NT'),
	('WNG', 'Wonogiri', 'Kabupaten', 'JT'),
	('WNO', 'Gunung Kidul', 'Kabupaten', 'YO'),
	('WNS', 'Sopeng', 'Kabupaten', 'SN'),
	('WRS', 'Keerom', 'Kabupaten', 'PA'),
	('WSB', 'Wonosobo', 'Kabupaten', 'JT'),
	('YYK', 'Yogyakarta', 'Kota', 'YO');
/*!40000 ALTER TABLE `kota` ENABLE KEYS */;

-- Dumping structure for table testprogrammer.user
CREATE TABLE IF NOT EXISTS `user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL DEFAULT '0',
  `email` varchar(50) NOT NULL DEFAULT '0',
  `pass` varchar(50) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Dumping data for table testprogrammer.user: ~0 rows (approximately)
DELETE FROM `user`;
/*!40000 ALTER TABLE `user` DISABLE KEYS */;
/*!40000 ALTER TABLE `user` ENABLE KEYS */;

-- Dumping structure for table testprogrammer.vendor
CREATE TABLE IF NOT EXISTS `vendor` (
  `vendor_name` varchar(150) DEFAULT NULL,
  `vendor_adress` varchar(150) DEFAULT NULL,
  `vendor_city` varchar(15) DEFAULT NULL,
  `vendor_postcode` varchar(6) DEFAULT NULL,
  `vendor_phone1` varchar(50) DEFAULT NULL,
  `vendor_phone2` varchar(50) DEFAULT NULL,
  `vendor_fax` varchar(50) DEFAULT NULL,
  `vendor_mail` varchar(50) DEFAULT NULL,
  `vendor_website` varchar(150) DEFAULT NULL,
  `vendor_companytype` char(5) DEFAULT NULL,
  `vendor_startyear` char(4) DEFAULT NULL,
  `vendor_PKP` bit(1) DEFAULT NULL,
  `vendor_companyname` varchar(75) DEFAULT NULL,
  `is_active` bit(1) DEFAULT b'1',
  `vendor_username` varchar(50) DEFAULT NULL,
  `vendor_companylogo` varchar(200) DEFAULT NULL,
  `vendor_lastmodified` datetime DEFAULT NULL,
  `vendor_id` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`vendor_id`),
  KEY `vendor_city` (`vendor_city`) USING BTREE,
  KEY `vendor_username` (`vendor_username`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AVG_ROW_LENGTH=1365;

-- Dumping data for table testprogrammer.vendor: ~0 rows (approximately)
DELETE FROM `vendor`;
/*!40000 ALTER TABLE `vendor` DISABLE KEYS */;
/*!40000 ALTER TABLE `vendor` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
